version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"  # Adjust the port if your backend runs on a different one
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3000:3000"  # Adjust the port if needed (React typically runs on 3000)
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  # Optionally add a database service if needed
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
